# The pinned codec and scaler headers both define PyroWave::Shaders with
# different layouts. Prepare only the C wrapper and scaler header in the build
# tree, preserving the shader/reflection payloads and canonical submodules.
function(polaris_prepare_pyrowave_scaler source output)
    set(paths pyrowave_c.cpp shaders/slangmosh_scaler.hpp)
    set(hashes
        46360aa52d5b11393607632cde6f9609dff341adefd1fe8b77dca47655c858fa
        a351b28ca1f1b949ef572786cc6cd560e382e8364fcbf8c89a8ff0da18d35d5d)
    foreach(index RANGE 0 1)
        list(GET paths ${index} path)
        list(GET hashes ${index} expected)
        file(SHA256 "${source}/${path}" actual)
        if(NOT actual STREQUAL expected)
            message(FATAL_ERROR "PyroWave scaler input changed: ${path}; review the namespace adaptation")
        endif()
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${source}/${path}")
        file(READ "${source}/${path}" content)
        if(index EQUAL 0)
            string(REPLACE "\tShaders<> shaders(" "\tPolarisPyroWaveScaler::Shaders<> shaders(" content "${content}")
        else()
            string(REPLACE "namespace PyroWave" "namespace PolarisPyroWaveScaler" content "${content}")
            string(REPLACE "SLANGMOSH_GENERATED_PyroWave" "SLANGMOSH_GENERATED_PolarisPyroWaveScaler" content "${content}")
        endif()
        get_filename_component(filename "${path}" NAME)
        set(destination "${output}/${filename}")
        set(previous "")
        if(EXISTS "${destination}")
            file(READ "${destination}" previous)
        endif()
        if(NOT previous STREQUAL content)
            file(WRITE "${destination}" "${content}")
        endif()
    endforeach()
endfunction()
